#Node.js base image 
FROM node:18.17.1-alpine
COPY package.json /

#INCLUDing dev dependencies

RUN npm install

#RUN webpack
COPY src/ /src
COPY webpack.config.js /
RUN npx webpack --config webpack.config.js 

COPY server/ /server
COPY dist/ /dist

CMD ["node", "server/index.js"]