SOURCE_URL="http://localhost:8080/geoserver"
AUTH="admin:geoserver"
WORKSPACE="ne"
OUT_DIR="geoserver_configs"
TARGET_URL="http://localhost:8080/geoserver"

# TRANSMISSION LINE CONFIG
DATASOURCE_NAME_TRANSMISSION="Transmission_Lines"
LAYER_NAME_TRANSMISSION="Electric_Power_Transmission_Lines_A"

# Download DATA SOURE CONFIG FOR TRANSMISSION LINE
curl -u $AUTH -X GET "$SOURCE_URL/rest/workspaces/$WORKSPACE/datastores/$DATASOURCE_NAME_TRANSMISSION.xml" -o "$OUT_DIR/$DATASOURCE_NAME_TRANSMISSION.xml"

# Download LAYER CONFIG FOR TRANSMISSION LINE
curl -u $AUTH -X GET "$TARGET_URL/rest/workspaces/$WORKSPACE/datastores/$DATASOURCE_NAME_TRANSMISSION/featuretypes/$LAYER_NAME_TRANSMISSION.xml" -o "$OUT_DIR/$LAYER_NAME_TRANSMISSION.xml"

#POWER_PLANT_CONFIG
DATASOURCE_NAME_POWER_PLANT="Power_Plant_Information"
LAYER_NAME_POWER_PLANT="Power_Plants"

# Download DATA SOURE CONFIG FOR POWER PLANT
curl -u $AUTH -X GET "$SOURCE_URL/rest/workspaces/$WORKSPACE/datastores/$DATASOURCE_NAME_POWER_PLANT.xml" -o "$OUT_DIR/$DATASOURCE_NAME_POWER_PLANT.xml"

# Download LAYER CONFIG FOR POWER PLANT
curl -u $AUTH -X GET "$TARGET_URL/rest/workspaces/$WORKSPACE/datastores/$DATASOURCE_NAME_POWER_PLANT/featuretypes/$LAYER_NAME_POWER_PLANT.xml" -o "$OUT_DIR/$LAYER_NAME_POWER_PLANT.xml"

# STATE MAP CONFIG
DATASOURCE_NAME_STATE_MAP=United_States_Map
LAYER_NAME_STATE_MAP=States_shapefile

# Download DATA SOURE CONFIG FOR STATE MAP
curl -u $AUTH -X GET "$SOURCE_URL/rest/workspaces/$WORKSPACE/datastores/$DATASOURCE_NAME_STATE_MAP.xml" -o "$OUT_DIR/$DATASOURCE_NAME_STATE_MAP.xml"

# Download LAYER CONFIG FOR STATE MAP
curl -u $AUTH -X GET "$TARGET_URL/rest/workspaces/$WORKSPACE/datastores/$DATASOURCE_NAME_STATE_MAP/featuretypes/$LAYER_NAME_STATE_MAP.xml" -o "$OUT_DIR/$LAYER_NAME_STATE_MAP.xml"
