name: Docker Push

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Geoserver Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: pcadler/geoserver-build:${{ github.ref_name }}
      - name: Build and Push Express Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.express
          push: true
          tags: pcadler/transmission-express:${{ github.ref_name }}
